/**
 * @file app/(routes)/trips/new/page.tsx
 * @description 픽업 그룹 생성 페이지
 *
 * 주요 기능:
 * 1. 제공자 픽업 그룹 생성
 * 2. 출발 예정 시각 및 그룹명 입력
 * 3. 초대는 별도 단계에서 진행
 *
 * 핵심 구현 로직:
 * - Client Component로 구현
 * - React Hook Form + Zod resolver로 폼 관리
 * - 출발 시간 입력 시 그룹명 자동 제안
 * - 제출 성공 시 Trip 목록 페이지로 리다이렉트
 *
 * @dependencies
 * - @/actions/trips: Server Action
 * - @/components/ui/card: 카드 컴포넌트
 * - @/components/ui/button: 버튼 컴포넌트
 * - @/components/ui/form: 폼 컴포넌트
 * - @/lib/validations/trip: Zod 스키마
 */

"use client";

import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { createTrip } from "@/actions/trips";
import { tripSchema, type TripFormData } from "@/lib/validations/trip";
import { generateGroupTitle } from "@/lib/utils/pickup-group";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Loader2 } from "lucide-react";

export const dynamic = "force-dynamic";

export default function NewTripPage() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [minDateTime, setMinDateTime] = useState<string>("");

  // 클라이언트에서만 min 값 설정 (Hydration 오류 방지)
  useEffect(() => {
    setMinDateTime(new Date().toISOString().slice(0, 16));
  }, []);

  const form = useForm<TripFormData>({
    resolver: zodResolver(tripSchema),
    defaultValues: {
      scheduled_start_at: "",
      title: "",
    },
  });

  // 출발 시간 변경 시 그룹명 자동 제안
  const scheduledStartAt = form.watch("scheduled_start_at");
  useEffect(() => {
    if (scheduledStartAt) {
      const autoTitle = generateGroupTitle(scheduledStartAt);
      // 현재 그룹명이 비어있거나 이전에 자동 생성된 값과 같으면 업데이트
      const currentTitle = form.getValues("title");
      // 자동 생성된 형식인지 확인 (예: "X월 X일 X시 픽업 그룹")
      const isAutoGenerated = /^\d+월 \d+일 \d+시 픽업 그룹$/.test(currentTitle);
      if (!currentTitle || isAutoGenerated) {
        form.setValue("title", autoTitle);
      }
    }
  }, [scheduledStartAt, form]);

  const onSubmit = async (data: TripFormData) => {
    setIsSubmitting(true);
    setSubmitError(null);

    try {
      const result = await createTrip({
        title: data.title,
        scheduled_start_at: data.scheduled_start_at,
      });

      if (!result.success) {
        setSubmitError(result.error || "픽업 그룹 생성에 실패했습니다.");
        setIsSubmitting(false);
        return;
      }

      // 성공 시 목록 페이지로 리다이렉트
      router.push("/trips");
    } catch (error) {
      console.error("픽업 그룹 생성 에러:", error);
      setSubmitError("예상치 못한 오류가 발생했습니다. 다시 시도해주세요.");
      setIsSubmitting(false);
    }
  };

  return (
    <div className="container mx-auto py-8 px-4 max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>새 픽업 제공</CardTitle>
          <CardDescription>
            제공자 전용: 새로운 픽업 그룹을 생성합니다. 출발 시간과 그룹명을 입력해주세요.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <div className="bg-blue-50 dark:bg-blue-950 p-4 rounded-md">
                <p className="text-sm text-blue-900 dark:text-blue-100">
                  <strong>안내:</strong> 픽업 그룹을 생성하면 요청자에게 초대를 보낼 수 있습니다.
                  각 픽업 그룹은 최대 3명까지 수용 가능합니다.
                </p>
              </div>

              {/* 에러 메시지 */}
              {submitError && (
                <div className="text-sm text-destructive bg-destructive/10 p-3 rounded-md">
                  {submitError}
                </div>
              )}

              {/* 출발 예정 시각 */}
              <FormField
                control={form.control}
                name="scheduled_start_at"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>출발 예정 시각</FormLabel>
                    <FormControl>
                      <Input
                        type="datetime-local"
                        {...field}
                        min={minDateTime}
                      />
                    </FormControl>
                    <FormDescription>
                      픽업 그룹의 출발 예정 시각을 선택해주세요.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* 그룹명 */}
              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>그룹명</FormLabel>
                    <FormControl>
                      <Input
                        {...field}
                        placeholder="예: 1월 7일 15시 픽업 그룹"
                      />
                    </FormControl>
                    <FormDescription>
                      픽업 그룹의 이름을 입력해주세요. 출발 시간을 입력하면 자동으로 제안됩니다.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* 제출 버튼 */}
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => router.back()}
                  disabled={isSubmitting}
                >
                  취소
                </Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  픽업 그룹 생성하기
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  );
}

